name: Febi Agil Ifdillah
description: Abstract but still well-read
url: "http://www.febiagil.me"

# Author info
author_name: Febi Agil Ifdillah
author_image_path: /images/author-image.jpg

# External services
github_url: "https://github.com/agilajah"
twitter_url: "https://twitter.com/_agilajah"
linkedin_url: "https://linkedin.com/in/febiagil"
feed_url: "http://feeds.feedburner.com/febiagil"
email: "febiagil20@gmail.com"

# Markdown rendering
kramdown:
  #  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /:categories/:year/:month/:day/:title/

# important since the site is compiled
# on Github's servers
timezone: America/New_York
